<?php

########################################################################
# Extension Manager/Repository config file for ext: "jhe_adventcalendar"
#
# Auto generated by Extension Builder 2013-11-05
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Adevntcalendar',
	'description' => 'A customizable advent calendar based on pages as content placeholders for the several wickets',
	'category' => 'plugin',
	'author' => 'Jari-Hermann Ernst',
	'author_email' => 'jari-hermann.ernst@bad-gmbh.de',
	'author_company' => 'B·A·D GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>